[package]
name = "tydi_derive_core"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
quote = "1"
proc-macro2 = "1.0"
# The full feature is important to access the Item types
syn = { version = "2.0", features = ["extra-traits", "full", "fold"] }
